import random
import asyncio
import math
import discord
from discord.ext import commands
intents = discord.Intents.default()
intents.members = True
intents.reactions = True
intents.messages = True
client = commands.Bot(command_prefix = 'c!', intents = intents)
client.remove_command("help")

@client.event
async def on_ready():
	activity = discord.Activity(name="<guild name>", type=3)
	await client.change_presence(status=discord.Status.online, activity=activity)
	print("Bot is ready!")

@client.command()
async def pt(ctx):
    embed = discord.Embed(title = "Periodic Table", color = discord.Colour.green())
    embed.set_image(url = "https://pubchem.ncbi.nlm.nih.gov/periodic-table/Periodic_Table.png")
    await ctx.send(embed = embed)

@client.command()
async def help(ctx):
    helppls = discord.Embed(title = ":white_check_mark: List of Commands", description = "Use the command prefix -> c!", color = discord.Colour.red())
    helppls.add_field(name = "c!pt", value = "Displays Periodic Table",inline = False)
    helppls.add_field(name = "c!element <elementname or elementnumber>", value = "Displays information about an element",inline = False)
    helppls.set_thumbnail(url = client.user.avatar_url)
    await ctx.send(embed = helppls)

@client.command()
async def element(ctx,element : str):
    if element == "Hydrogen" or element == "hydrogen" or element == "1":
        embed2 = discord.Embed(title = "`HYDROGEN`", color = discord.Colour.blue())
        embed2.add_field(name = "❯ **Name**", value = "Hydrogen")
        embed2.add_field(name = "❯ **Atomic Symbol**", value = "H",inline = True)
        embed2.add_field(name = "❯ **Atomic Number**", value = "1")
        embed2.add_field(name = "❯ **Atomic Mass**", value = "1.008u",inline = True)
        embed2.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed2.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed2.add_field(name = "❯ **Valency**", value = "1")
        embed2.add_field(name = "❯ **First Ionization energy**", value = "1312 KJ/mol",inline = True)
        embed2.add_field(name = "❯ **Atomic Radius**", value = "25 pm")
        embed2.add_field(name = "❯ **Isotopes**", value = "H (mass = 1, 99.985%), D(mass = 2, 1.5*(10^-4)), T (mass = 3, unstable)",inline = False)
        embed2.set_thumbnail(url = "https://sciencenotes.org/wp-content/uploads/2015/04/Hydrogen_Tile-300x300.png")
        await ctx.send(embed = embed2)
    elif element == "Helium" or element == "helium" or element == "2":
        embed3 = discord.Embed(title = "`HELIUM`", color = discord.Colour.blue())
        embed3.add_field(name = "❯ **Name**", value = "Helium")
        embed3.add_field(name = "❯ **Atomic Symbol**", value = "He",inline = True)
        embed3.add_field(name = "❯ **Atomic Number**", value = "2")
        embed3.add_field(name = "❯ **Atomic Mass**", value = "4.002602u",inline = True)
        embed3.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed3.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed3.add_field(name = "❯ **Valency**", value = "0")
        embed3.add_field(name = "❯ **First Ionization energy**", value = "2372.3 KJ/mol",inline = True)
        embed3.add_field(name = "❯ **Atomic Radius**", value = "31 pm")
        embed3.add_field(name = "❯ **Isotopes**", value = "He (mass = 4, 99.999863%), He (mass = 3, 1.37*(10^-6)), He (mass = 6, unstable)",inline = False)
        embed3.set_thumbnail(url = "https://res.cloudinary.com/teepublic/image/private/s--uaEm9S9U--/c_crop,x_10,y_10/c_fit,h_1109/c_crop,g_north_west,h_1260,w_1260,x_-76,y_-76/co_rgb:0f7b47,e_colorize,u_Misc:One%20Pixel%20Gray/c_scale,g_north_west,h_1260,w_1260/fl_layer_apply,g_north_west,x_-76,y_-76/bo_180px_solid_white/e_overlay,fl_layer_apply,h_1260,l_Misc:Art%20Print%20Bumpmap,w_1260/e_shadow,x_6,y_6/c_limit,h_1134,w_1134/c_lpad,g_center,h_1260,w_1260/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1548470359/production/designs/4081193_0.jpg")
        await ctx.send(embed = embed3)
    elif element == "Lithium" or element == "lithium" or element == "3":
        embed4 = discord.Embed(title = "`LITHIUM`", color = discord.Colour.blue())
        embed4.add_field(name = "❯ **Name**", value = "Lithium")
        embed4.add_field(name = "❯ **Atomic Symbol**", value = "Li",inline = True)
        embed4.add_field(name = "❯ **Atomic Number**", value = "3")
        embed4.add_field(name = "❯ **Atomic Mass**", value = "6.94u",inline = True)
        embed4.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed4.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed4.add_field(name = "❯ **Valency**", value = "1")
        embed4.add_field(name = "❯ **First Ionization energy**", value = "520.2 KJ/mol",inline = True)
        embed4.add_field(name = "❯ **Atomic Radius**", value = "145 pm")
        embed4.add_field(name = "❯ **Isotopes**", value = "Li (mass = 6, 92.41%), Li (mass = 7, 7.59%), Li (mass = 8, unstable)",inline = False)
        embed4.set_thumbnail(url = "https://www.theenergyreport.com/images/AS_LithiumSymbol11-18-900.jpg")
        await ctx.send(embed = embed4)
    elif element == "Beryllium" or element == "beryllium" or element == "4":
        embed5 = discord.Embed(title = "`BERYLLIUM`", color = discord.Colour.blue())
        embed5.add_field(name = "❯ **Name**", value = "Beryllium")
        embed5.add_field(name = "❯ **Atomic Symbol**", value = "Be",inline = True)
        embed5.add_field(name = "❯ **Atomic Number**", value = "4")
        embed5.add_field(name = "❯ **Atomic Mass**", value = "9.0121831u",inline = True)
        embed5.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed5.add_field(name = "❯ **Colour**", value = "Stale Grey",inline = True)
        embed5.add_field(name = "❯ **Valency**", value = "2")
        embed5.add_field(name = "❯ **First Ionization energy**", value = "899.5 KJ/mol",inline = True)
        embed5.add_field(name = "❯ **Atomic Radius**", value = "105 pm")
        embed5.add_field(name = "❯ **Isotopes**", value = "Be (mass = 9, 100%), Be (mass = 10, unstable)",inline = False)
        embed5.set_thumbnail(url = "https://base.imgix.net/files/base/ebm/foundrymag/image/2019/03/foundrymag_4190_thinkstockphotos_beryllium_element_800.png?auto=format&fit=max&w=1200")
        await ctx.send(embed = embed5)
    elif element == "Boron" or element == "boron" or element == "5":
        embed6 = discord.Embed(title = "`BORON`", color = discord.Colour.blue())
        embed6.add_field(name = "❯ **Name**", value = "Boron")
        embed6.add_field(name = "❯ **Atomic Symbol**", value = "B",inline = True)
        embed6.add_field(name = "❯ **Atomic Number**", value = "5")
        embed6.add_field(name = "❯ **Atomic Mass**", value = "10.81u",inline = True)
        embed6.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed6.add_field(name = "❯ **Colour**", value = "Black",inline = True)
        embed6.add_field(name = "❯ **Valency**", value = "3")
        embed6.add_field(name = "❯ **First Ionization energy**", value = "800.6 KJ/mol",inline = True)
        embed6.add_field(name = "❯ **Atomic Radius**", value = "85 pm")
        embed6.add_field(name = "❯ **Isotopes**", value = "B (mass = 11, 80.2%), B (mass = 10, 19.8%), B (mass = 8, unstable)",inline = False)
        embed6.set_thumbnail(url = "https://images.pond5.com/boron-element-5-periodic-table-footage-119222080_iconl.jpeg")
        await ctx.send(embed = embed6)
    elif element == "Carbon" or element == "carbon" or element == "6":
        embed7 = discord.Embed(title = "`CARBON`", color = discord.Colour.blue())
        embed7.add_field(name = "❯ **Name**", value = "Carbon")
        embed7.add_field(name = "❯ **Atomic Symbol**", value = "C",inline = True)
        embed7.add_field(name = "❯ **Atomic Number**", value = "6")
        embed7.add_field(name = "❯ **Atomic Mass**", value = "12.011u",inline = True)
        embed7.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed7.add_field(name = "❯ **Colour**", value = "Black",inline = True)
        embed7.add_field(name = "❯ **Valency**", value = "4")
        embed7.add_field(name = "❯ **First Ionization energy**", value = "1086.5 KJ/mol",inline = True)
        embed7.add_field(name = "❯ **Atomic Radius**", value = "70 pm")
        embed7.add_field(name = "❯ **Isotopes**", value = "C (mass = 12, 98.89%), C (mass = 13, 1.11%), C (mass = 14, unstable)",inline = False)
        embed7.set_thumbnail(url = "https://t4.ftcdn.net/jpg/01/77/79/97/360_F_177799740_crXhROUkoc7Z9I9JtweYoBfjqNiGit5A.jpg")
        await ctx.send(embed = embed7)
    elif element == "Nitrogen" or element == "nitrogen" or element == "7":
        embed8 = discord.Embed(title = "`NITROGEN`", color = discord.Colour.blue())
        embed8.add_field(name = "❯ **Name**", value = "Nitrogen")
        embed8.add_field(name = "❯ **Atomic Symbol**", value = "N",inline = True)
        embed8.add_field(name = "❯ **Atomic Number**", value = "7")
        embed8.add_field(name = "❯ **Atomic Mass**", value = "14.007u",inline = True)
        embed8.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed8.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed8.add_field(name = "❯ **Valency**", value = "3")
        embed8.add_field(name = "❯ **First Ionization energy**", value = "1402.3 KJ/mol",inline = True)
        embed8.add_field(name = "❯ **Atomic Radius**", value = "65 pm")
        embed8.add_field(name = "❯ **Isotopes**", value = "N (mass = 14, 99.634%), N (mass = 15, 0.366%), N (mass = 13, unstable)",inline = False)
        embed8.set_thumbnail(url = "https://t3.ftcdn.net/jpg/01/93/19/66/360_F_193196642_F8ImI09Z5J3LqRlsGxt8QjbiGJpmZbnf.jpg")
        await ctx.send(embed = embed8)
    elif element == "Oxygen" or element == "oxygen" or element == "8":
        embed9 = discord.Embed(title = "`OXYGEN`", color = discord.Colour.blue())
        embed9.add_field(name = "❯ **Name**", value = "Oxygen")
        embed9.add_field(name = "❯ **Atomic Symbol**", value = "O",inline = True)
        embed9.add_field(name = "❯ **Atomic Number**", value = "8")
        embed9.add_field(name = "❯ **Atomic Mass**", value = "15.999u",inline = True)
        embed9.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed9.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed9.add_field(name = "❯ **Valency**", value = "2")
        embed9.add_field(name = "❯ **First Ionization energy**", value = "1313.9 KJ/mol",inline = True)
        embed9.add_field(name = "❯ **Atomic Radius**", value = "60 pm")
        embed9.add_field(name = "❯ **Isotopes**", value = "O (mass = 16, 99.762%), Be (mass = 15, unstable)",inline = False)
        embed9.set_thumbnail(url = "https://images.ctfassets.net/cnu0m8re1exe/4AVmagUwOTacKuNyFnT3Ln/7f4a078abf445c701d6bfb6de237a0e7/oxygen.jpg?w=650&h=433&fit=fill")
        await ctx.send(embed = embed9)
    elif element == "Flourine" or element == "flourine" or element == "9":
        embed10 = discord.Embed(title = "`FLOURINE`", color = discord.Colour.blue())
        embed10.add_field(name = "❯ **Name**", value = "Flourine")
        embed10.add_field(name = "❯ **Atomic Symbol**", value = "F",inline = True)
        embed10.add_field(name = "❯ **Atomic Number**", value = "9")
        embed10.add_field(name = "❯ **Atomic Mass**", value = "18.998403163u",inline = True)
        embed10.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed10.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed10.add_field(name = "❯ **Valency**", value = "1")
        embed10.add_field(name = "❯ **First Ionization energy**", value = "1681 KJ/mol",inline = True)
        embed10.add_field(name = "❯ **Atomic Radius**", value = "50 pm")
        embed10.add_field(name = "❯ **Isotopes**", value = "F (mass = 19, 100%), F (mass = 18, unstable)",inline = False)
        embed10.set_thumbnail(url = "https://lh3.googleusercontent.com/proxy/WxemTQpHbcAr1Z5Uu7UEpa5TSFJDNQQjNYRAEZj8ThBpRStjM_OOI7ZpAEpuaAPf3ldH1tR_PyzcSoea-VQ6ZG70O4_Tn4pr0dEkRUTIrTCtmg")
        await ctx.send(embed = embed10)
    elif element == "Neon" or element == "neon" or element == "10":
        embed11 = discord.Embed(title = "`NEON`", color = discord.Colour.blue())
        embed11.add_field(name = "❯ **Name**", value = "Neon")
        embed11.add_field(name = "❯ **Atomic Symbol**", value = "Ne",inline = True)
        embed11.add_field(name = "❯ **Atomic Number**", value = "10")
        embed11.add_field(name = "❯ **Atomic Mass**", value = "20.1797u",inline = True)
        embed11.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed11.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed11.add_field(name = "❯ **Valency**", value = "0")
        embed11.add_field(name = "❯ **First Ionization energy**", value = "2080.7 KJ/mol",inline = True)
        embed11.add_field(name = "❯ **Atomic Radius**", value = "65 pm")
        embed11.add_field(name = "❯ **Isotopes**", value = "Ne (mass = 20, 90.48%), Ne (mass = 22, 9.25%), Ne (mass = 21, 0.27%), Ne (mass = 24, unstable)",inline = False)
        embed11.set_thumbnail(url = "https://pixfeeds.com/images/science/chemistry/1280-482504363-neon-element.jpg")
        await ctx.send(embed = embed11)
    elif element == "Sodium" or element == "sodium" or element == "11":
        embed12 = discord.Embed(title = "`SODIUM`", color = discord.Colour.blue())
        embed12.add_field(name = "❯ **Name**", value = "Sodium")
        embed12.add_field(name = "❯ **Atomic Symbol**", value = "Na",inline = True)
        embed12.add_field(name = "❯ **Atomic Number**", value = "11")
        embed12.add_field(name = "❯ **Atomic Mass**", value = "22.98976928u",inline = True)
        embed12.add_field(name = "❯ **Phase at STP**", value = "Sodium")
        embed12.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed12.add_field(name = "❯ **Valency**", value = "1")
        embed12.add_field(name = "❯ **First Ionization energy**", value = "495.8 KJ/mol",inline = True)
        embed12.add_field(name = "❯ **Atomic Radius**", value = "180 pm")
        embed12.add_field(name = "❯ **Isotopes**", value = "Na (mass = 23, 90.48%), Ne (mass = 22, unstable)",inline = False)
        embed12.set_thumbnail(url = "https://cdn1.byjus.com/chemistry/2017/05/22074824/Sodium_Tile-300x300.png")
        await ctx.send(embed = embed12)
    elif element == "Magnesium" or element == "magnesium" or element == "12":
        embed13 = discord.Embed(title = "`MAGNESIUM`", color = discord.Colour.blue())
        embed13.add_field(name = "❯ **Name**", value = "Magnesium")
        embed13.add_field(name = "❯ **Atomic Symbol**", value = "Mg",inline = True)
        embed13.add_field(name = "❯ **Atomic Number**", value = "12")
        embed13.add_field(name = "❯ **Atomic Mass**", value = "24.305u",inline = True)
        embed13.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed13.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed13.add_field(name = "❯ **Valency**", value = "2")
        embed13.add_field(name = "❯ **First Ionization energy**", value = "737.7 KJ/mol",inline = True)
        embed13.add_field(name = "❯ **Atomic Radius**", value = "150 pm")
        embed13.add_field(name = "❯ **Isotopes**", value = "Mg (mass = 24, 78.99%), Mg (mass = 26, 11.01%), Mg (mass = 25, 10%), Mg (mass = 28, unstable)",inline = False)
        embed13.set_thumbnail(url = "https://sciencenotes.org/wp-content/uploads/2015/04/Magnesium_Tile.png")
        await ctx.send(embed = embed13)
    elif element == "Aluminium" or element == "aluminium" or element == "13":
        embed14 = discord.Embed(title = "`ALUMINIUM`", color = discord.Colour.blue())
        embed14.add_field(name = "❯ **Name**", value = "Aluminium")
        embed14.add_field(name = "❯ **Atomic Symbol**", value = "Al",inline = True)
        embed14.add_field(name = "❯ **Atomic Number**", value = "13")
        embed14.add_field(name = "❯ **Atomic Mass**", value = "26.9815358u",inline = True)
        embed14.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed14.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed14.add_field(name = "❯ **Valency**", value = "3")
        embed14.add_field(name = "❯ **First Ionization energy**", value = "577.5 KJ/mol",inline = True)
        embed14.add_field(name = "❯ **Atomic Radius**", value = "125 pm")
        embed14.add_field(name = "❯ **Isotopes**", value = "Al (mass = 27, 100%), Al (mass = 26, unstable)",inline = False)
        embed14.set_thumbnail(url = "https://thumb.mp-farm.com/8733991/preview.jpg")
        await ctx.send(embed = embed14)
    elif element == "Silicon" or element == "silicon" or element == "14":
        embed15 = discord.Embed(title = "`SILICON`", color = discord.Colour.blue())
        embed15.add_field(name = "❯ **Name**", value = "Silicon")
        embed15.add_field(name = "❯ **Atomic Symbol**", value = "Si",inline = True)
        embed15.add_field(name = "❯ **Atomic Number**", value = "14")
        embed15.add_field(name = "❯ **Atomic Mass**", value = "28.085u",inline = True)
        embed15.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed15.add_field(name = "❯ **Colour**", value = "Grey",inline = True)
        embed15.add_field(name = "❯ **Valency**", value = "4")
        embed15.add_field(name = "❯ **First Ionization energy**", value = "786.5 KJ/mol",inline = True)
        embed15.add_field(name = "❯ **Atomic Radius**", value = "110 pm")
        embed15.add_field(name = "❯ **Isotopes**", value = "Si (mass = 28, 92.23%), Si(mass = 29, 4.683%),Si (mass = 30, 3.087%), Si (mass = 32, unstable)",inline = False)
        embed15.set_thumbnail(url = "https://pixfeeds.com/images/4/273340/1200-482504395-silicon-symbol.jpg")
        await ctx.send(embed = embed15)
    elif element == "Phosphorus" or element == "phosphorus" or element == "15":
        embed16 = discord.Embed(title = "`PHOSPHORUS`", color = discord.Colour.blue())
        embed16.add_field(name = "❯ **Name**", value = "Phophorus")
        embed16.add_field(name = "❯ **Atomic Symbol**", value = "P",inline = True)
        embed16.add_field(name = "❯ **Atomic Number**", value = "15")
        embed16.add_field(name = "❯ **Atomic Mass**", value = "30.973761998u",inline = True)
        embed16.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed16.add_field(name = "❯ **Colour**", value = "White,Red,Black",inline = True)
        embed16.add_field(name = "❯ **Valency**", value = "5")
        embed16.add_field(name = "❯ **First Ionization energy**", value = "1011.8 KJ/mol",inline = True)
        embed16.add_field(name = "❯ **Atomic Radius**", value = "100 pm")
        embed16.add_field(name = "❯ **Isotopes**", value = "P (mass = 31, 100%), Al (mass = 33, unstable)",inline = False)
        embed16.set_thumbnail(url = "https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX31418379.jpg")
        await ctx.send(embed = embed16)
    elif element == "Sulphur" or element == "sulphur" or element == "16":
        embed17 = discord.Embed(title = "`SULPHUR`", color = discord.Colour.blue())
        embed17.add_field(name = "❯ **Name**", value = "Sulphur")
        embed17.add_field(name = "❯ **Atomic Symbol**", value = "S",inline = True)
        embed17.add_field(name = "❯ **Atomic Number**", value = "16")
        embed17.add_field(name = "❯ **Atomic Mass**", value = "32.06u",inline = True)
        embed17.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed17.add_field(name = "❯ **Colour**", value = "Yellow",inline = True)
        embed17.add_field(name = "❯ **Valency**", value = "6")
        embed17.add_field(name = "❯ **First Ionization energy**", value = "999.6 KJ/mol",inline = True)
        embed17.add_field(name = "❯ **Atomic Radius**", value = "100 pm")
        embed17.add_field(name = "❯ **Isotopes**", value = "S (mass = 32, 95.02%), S (mass = 34, 4.21%), S (mass = 33, 0.75%), S (mass = 36, 2*(10^-4)), S (mass = 35, unstable)",inline = False)
        embed17.set_thumbnail(url = "https://as1.ftcdn.net/jpg/02/03/52/70/500_F_203527082_iG5R8ekwW2gMvnv0wmKTeAo1VV8chWsG.jpg")
        await ctx.send(embed = embed17)
    elif element == "Chlorine" or element == "chlorine" or element == "17":
        embed18 = discord.Embed(title = "`CHLORINE`", color = discord.Colour.blue())
        embed18.add_field(name = "❯ **Name**", value = "Cholrine")
        embed18.add_field(name = "❯ **Atomic Symbol**", value = "Cl",inline = True)
        embed18.add_field(name = "❯ **Atomic Number**", value = "17")
        embed18.add_field(name = "❯ **Atomic Mass**", value = "35.45u",inline = True)
        embed18.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed18.add_field(name = "❯ **Colour**", value = "Yellow",inline = True)
        embed18.add_field(name = "❯ **Valency**", value = "5")
        embed18.add_field(name = "❯ **First Ionization energy**", value = "1251.2 KJ/mol",inline = True)
        embed18.add_field(name = "❯ **Atomic Radius**", value = "100 pm")
        embed18.add_field(name = "❯ **Isotopes**", value = "Cl (mass = 35, 75.77%),Cl (mass = 37, 24.23%),Cl (mass = 36, unstable)",inline = False)
        embed18.set_thumbnail(url = "https://www.thoughtco.com/thmb/tKzMigPZgKHFt2Ii37lCZUmZs3Y=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-186451129-58c229555f9b58af5cd41fdf.jpg")
        await ctx.send(embed = embed18)
    elif element == "Argon" or element == "argon" or element == "18":
        embed19 = discord.Embed(title = "`ARGON`", color = discord.Colour.blue())
        embed19.add_field(name = "❯ **Name**", value = "Argon")
        embed19.add_field(name = "❯ **Atomic Symbol**", value = "Ar",inline = True)
        embed19.add_field(name = "❯ **Atomic Number**", value = "18")
        embed19.add_field(name = "❯ **Atomic Mass**", value = "39.948u",inline = True)
        embed19.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed19.add_field(name = "❯ **Colour**", value = "Colourless",inline = True)
        embed19.add_field(name = "❯ **Valency**", value = "0")
        embed19.add_field(name = "❯ **First Ionization energy**", value = "1520.6 KJ/mol",inline = True)
        embed19.add_field(name = "❯ **Atomic Radius**", value = "71 pm")
        embed19.add_field(name = "❯ **Isotopes**", value = "Ar (mass = 40, 99.6003%),Ar (mass = 36, 0.3365%),Ar (mass = 38, 6.32*(10^-4)), Ar (mass = 39, Unstable)",inline = False)
        embed19.set_thumbnail(url = "https://thumbs.dreamstime.com/b/argon-ar-chemical-element-d-rendering-argon-ar-chemical-element-d-rendering-isolated-black-background-110410303.jpg")
        await ctx.send(embed = embed19)
    elif element == "Potassium" or element == "potassium" or element == "19":
        embed20 = discord.Embed(title = "`POTASSIUM`", color = discord.Colour.blue())
        embed20.add_field(name = "❯ **Name**", value = "Potassium")
        embed20.add_field(name = "❯ **Atomic Symbol**", value = "K",inline = True)
        embed20.add_field(name = "❯ **Atomic Number**", value = "19")
        embed20.add_field(name = "❯ **Atomic Mass**", value = "39.0983u",inline = True)
        embed20.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed20.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed20.add_field(name = "❯ **Valency**", value = "1")
        embed20.add_field(name = "❯ **First Ionization energy**", value = "418.8 KJ/mol",inline = True)
        embed20.add_field(name = "❯ **Atomic Radius**", value = "220 pm")
        embed20.add_field(name = "❯ **Isotopes**", value = "K (mass = 39, 93.25%), K (mass = 41, 6.73%), K (mass = 40, Unstable)",inline = False)
        embed20.set_thumbnail(url = "https://thumbs.dreamstime.com/b/potassium-k-chemical-element-d-rendering-potassium-k-chemical-element-d-rendering-isolated-black-background-110410463.jpg")
        await ctx.send(embed = embed20)
    elif element == "Calcium" or element == "calcium" or element == "20":
        embed21 = discord.Embed(title = "`CALCIUM`", color = discord.Colour.blue())
        embed21.add_field(name = "❯ **Name**", value = "Calcium")
        embed21.add_field(name = "❯ **Atomic Symbol**", value = "Ca",inline = True)
        embed21.add_field(name = "❯ **Atomic Number**", value = "20")
        embed21.add_field(name = "❯ **Atomic Mass**", value = "40.078u",inline = True)
        embed21.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed21.add_field(name = "❯ **Colour**", value = "White",inline = True)
        embed21.add_field(name = "❯ **Valency**", value = "2")
        embed21.add_field(name = "❯ **First Ionization energy**", value = "589.8 KJ/mol",inline = True)
        embed21.add_field(name = "❯ **Atomic Radius**", value = "180 pm")
        embed21.add_field(name = "❯ **Isotopes**", value = "Ca (mass = 40, 96.94%), Ca (mass = 48, Unstable)",inline = False)
        embed21.set_thumbnail(url = "https://t3.ftcdn.net/jpg/01/93/19/54/360_F_193195436_00B9Ub0sYEC9jK2lp9qL3bAUZX22djwU.jpg")
        await ctx.send(embed = embed21)
    elif element == "Scandium" or element == "scandium" or element == "21":
        embed22 = discord.Embed(title = "`SCANDIUM`", color = discord.Colour.blue())
        embed22.add_field(name = "❯ **Name**", value = "Scandium")
        embed22.add_field(name = "❯ **Atomic Symbol**", value = "Sc",inline = True)
        embed22.add_field(name = "❯ **Atomic Number**", value = "21")
        embed22.add_field(name = "❯ **Atomic Mass**", value = "44.955u",inline = True)
        embed22.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed22.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed22.add_field(name = "❯ **Valency**", value = "3")
        embed22.add_field(name = "❯ **First Ionization energy**", value = "633.1 KJ/mol",inline = True)
        embed22.add_field(name = "❯ **Atomic Radius**", value = "160 pm")
        embed22.add_field(name = "❯ **Isotopes**", value = "Sc(mass = 45, 100%), Sc (mass = 46, Unstable),",inline = False)
        embed22.set_thumbnail(url = "https://as2.ftcdn.net/jpg/02/63/83/37/500_F_263833761_TPsGPcPpWaWBdWXtjUPuTYdI39pwU8bo.jpg")
        await ctx.send(embed = embed22)
    elif element == "Titanium" or element == "titanium" or element == "22":
        embed23 = discord.Embed(title = "`TITANIUM`", color = discord.Colour.blue())
        embed23.add_field(name = "❯ **Name**", value = "Titanium")
        embed23.add_field(name = "❯ **Atomic Symbol**", value = "Ti",inline = True)
        embed23.add_field(name = "❯ **Atomic Number**", value = "22")
        embed23.add_field(name = "❯ **Atomic Mass**", value = "47.867u",inline = True)
        embed23.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed23.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed23.add_field(name = "❯ **Valency**", value = "4")
        embed23.add_field(name = "❯ **First Ionization energy**", value = "658.8 KJ/mol",inline = True)
        embed23.add_field(name = "❯ **Atomic Radius**", value = "140 pm")
        embed23.add_field(name = "❯ **Isotopes**", value = "Ti (mass = 48, 73.72%), Ti (mass = 44, unstable)",inline = False)
        embed23.set_thumbnail(url = "https://theodoregray.com/periodictable/Tiles/022/s14.JPG")
        await ctx.send(embed = embed23)
    elif element == "Vanadium" or element == "vanadium" or element == "23":
        embed24 = discord.Embed(title = "`VANADIUM`", color = discord.Colour.blue())
        embed24.add_field(name = "❯ **Name**", value = "Vanadium")
        embed24.add_field(name = "❯ **Atomic Symbol**", value = "V",inline = True)
        embed24.add_field(name = "❯ **Atomic Number**", value = "23")
        embed24.add_field(name = "❯ **Atomic Mass**", value = "50.94u",inline = True)
        embed24.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed24.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed24.add_field(name = "❯ **Valency**", value = "5")
        embed24.add_field(name = "❯ **First Ionization energy**", value = "650.9 KJ/mol",inline = True)
        embed24.add_field(name = "❯ **Atomic Radius**", value = "135 pm")
        embed24.add_field(name = "❯ **Isotopes**", value = "V (mass = 50, 99.75%), V (mass = 51)",inline = False)
        embed24.set_thumbnail(url = "https://as1.ftcdn.net/jpg/01/57/16/88/500_F_157168886_00kyiPcfpW21eK88YVxehWEkYVeg0Kor.jpg")
        await ctx.send(embed = embed24)
    elif element == "Chromium" or element == "chromium" or element == "24":
        embed25 = discord.Embed(title = "`CHROMIUM`", color = discord.Colour.blue())
        embed25.add_field(name = "❯ **Name**", value = "Chormium")
        embed25.add_field(name = "❯ **Atomic Symbol**", value = "Cr",inline = True)
        embed25.add_field(name = "❯ **Atomic Number**", value = "24")
        embed25.add_field(name = "❯ **Atomic Mass**", value = "51.9966u",inline = True)
        embed25.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed25.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed25.add_field(name = "❯ **Valency**", value = "6")
        embed25.add_field(name = "❯ **First Ionization energy**", value = "652.9 KJ/mol",inline = True)
        embed25.add_field(name = "❯ **Atomic Radius**", value = "140 pm")
        embed25.add_field(name = "❯ **Isotopes**", value = "Cr (mass = 51, 83.78%), Cr (mass = 52, unstable)",inline = False)
        embed25.set_thumbnail(url = "https://thumbs.dreamstime.com/b/chromium-cr-chemical-element-d-rendering-chromium-cr-chemical-element-d-rendering-isolated-black-background-110410337.jpg")
        await ctx.send(embed = embed25)
    elif element == "Manganese" or element == "manganese" or element == "25":
        embed26 = discord.Embed(title = "`MANGANESE`", color = discord.Colour.blue())
        embed26.add_field(name = "❯ **Name**", value = "Manganese")
        embed26.add_field(name = "❯ **Atomic Symbol**", value = "Mn",inline = True)
        embed26.add_field(name = "❯ **Atomic Number**", value = "25")
        embed26.add_field(name = "❯ **Atomic Mass**", value = "54.9386u",inline = True)
        embed26.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed26.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed26.add_field(name = "❯ **Valency**", value = "4")
        embed26.add_field(name = "❯ **First Ionization energy**", value = "717.3 KJ/mol",inline = True)
        embed26.add_field(name = "❯ **Atomic Radius**", value = "140 pm")
        embed26.add_field(name = "❯ **Isotopes**", value = "Mn (mass = 55, 100%), Mn (mass = 53)",inline = False)
        embed26.set_thumbnail(url = "https://www.sciencepicture.co/_img/search/Manganese-Chemical-Element_spc-id-5048.jpg")
        await ctx.send(embed = embed26)
    elif element == "Iron" or element == "iron" or element == "26":
        embed27 = discord.Embed(title = "`IRON`", color = discord.Colour.blue())
        embed27.add_field(name = "❯ **Name**", value = "Iron")
        embed27.add_field(name = "❯ **Atomic Symbol**", value = "Fe",inline = True)
        embed27.add_field(name = "❯ **Atomic Number**", value = "26")
        embed27.add_field(name = "❯ **Atomic Mass**", value = "55.845u",inline = True)
        embed27.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed27.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed27.add_field(name = "❯ **Valency**", value = "3")
        embed27.add_field(name = "❯ **First Ionization energy**", value = "762.5 KJ/mol",inline = True)
        embed27.add_field(name = "❯ **Atomic Radius**", value = "140 pm")
        embed27.add_field(name = "❯ **Isotopes**", value = "Fe (mass = 56, 91.75%), Fe (mass = 54, 5.845%), Fe (mass = 57, 2.119%), Fe (mass = 60, unstable)",inline = False)
        embed27.set_thumbnail(url = "https://t4.ftcdn.net/jpg/01/93/19/59/360_F_193195925_7VFTJEUgqhemWUDvtQqJDFYCFFEOQ6MN.jpg")
        await ctx.send(embed = embed27)
    elif element == "Cobalt" or element == "cobalt" or element == "27":
        embed28 = discord.Embed(title = "`CHROMIUM`", color = discord.Colour.blue())
        embed28.add_field(name = "❯ **Name**", value = "Cobalt")
        embed28.add_field(name = "❯ **Atomic Symbol**", value = "Co",inline = True)
        embed28.add_field(name = "❯ **Atomic Number**", value = "27")
        embed28.add_field(name = "❯ **Atomic Mass**", value = "58.983u",inline = True)
        embed28.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed28.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed28.add_field(name = "❯ **Valency**", value = "4")
        embed28.add_field(name = "❯ **First Ionization energy**", value = "760.4 KJ/mol",inline = True)
        embed28.add_field(name = "❯ **Atomic Radius**", value = "135 pm")
        embed28.add_field(name = "❯ **Isotopes**", value = "Co (mass = 59, 100%), Co (mass = 60, unstable)",inline = False)
        embed28.set_thumbnail(url = "https://w7.pngwing.com/pngs/75/665/png-transparent-periodic-table-chemical-element-iron-symbol-lawrencium-tin-chemical-element-electronics-chemistry.png")
        await ctx.send(embed = embed28)
    elif element == "Nickel" or element == "nickel" or element == "28":
        embed29 = discord.Embed(title = "`NICKEL`", color = discord.Colour.blue())
        embed29.add_field(name = "❯ **Name**", value = "Nickel")
        embed29.add_field(name = "❯ **Atomic Symbol**", value = "Ni",inline = True)
        embed29.add_field(name = "❯ **Atomic Number**", value = "28")
        embed29.add_field(name = "❯ **Atomic Mass**", value = "58.693u",inline = True)
        embed29.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed29.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed29.add_field(name = "❯ **Valency**", value = "2")
        embed29.add_field(name = "❯ **First Ionization energy**", value = "727.1 KJ/mol",inline = True)
        embed29.add_field(name = "❯ **Atomic Radius**", value = "135 pm")
        embed29.add_field(name = "❯ **Isotopes**", value = "Ni (mass = 58, 68.07%),Ni (mass = 60, 26.223%), Ni (mass = 59, unstable)",inline = False)
        embed29.set_thumbnail(url = "https://media.istockphoto.com/vectors/nickel-chemical-element-vector-id1127314361")
        await ctx.send(embed = embed29)
    elif element == "Copper" or element == "copper" or element == "29":
        embed30 = discord.Embed(title = "`COPPER`", color = discord.Colour.blue())
        embed30.add_field(name = "❯ **Name**", value = "Copper")
        embed30.add_field(name = "❯ **Atomic Symbol**", value = "Cu",inline = True)
        embed30.add_field(name = "❯ **Atomic Number**", value = "29")
        embed30.add_field(name = "❯ **Atomic Mass**", value = "63.546u",inline = True)
        embed30.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed30.add_field(name = "❯ **Colour**", value = "Copper",inline = True)
        embed30.add_field(name = "❯ **Valency**", value = "2")
        embed30.add_field(name = "❯ **First Ionization eZnrgy**", value = "745.5 KJ/mol",inline = True)
        embed30.add_field(name = "❯ **Atomic Radius**", value = "135 pm")
        embed30.add_field(name = "❯ **Isotopes**", value = "Cu (mass = 63, 69.17%), Cu (mass = 65, 30.83%), Cu (mass = 67, 61.83%)",inline = False)
        embed30.set_thumbnail(url = "https://thumbs.dreamstime.com/b/copper-cu-chemical-element-d-rendering-black-background-110410355.jpg")
        await ctx.send(embed = embed30)
    elif element == "Gallium"or element == "gallium" or element == "31":
        embed31 = discord.Embed(title = "`GALLIUM`", color = discord.Colour.blue())
        embed31.add_field(name = "❯ **Name**", value = "Gallium")
        embed31.add_field(name = "❯ **Atomic Symbol**", value = "Ga",inline = True)
        embed31.add_field(name = "❯ **Atomic Number**", value = "31")
        embed31.add_field(name = "❯ **Atomic Mass**", value = "69.732u",inline = True)
        embed31.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed31.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed31.add_field(name = "❯ **Valency**", value = "3")
        embed31.add_field(name = "❯ **First Ionization energy**", value = "578.8 KJ/mol",inline = True)
        embed31.add_field(name = "❯ **Atomic Radius**", value = "130 pm")
        embed31.add_field(name = "❯ **Isotopes**", value = "Ga (mass = 69, 60.108%), Ga (mass = 71, 39.892), Ga (mass = 67, unstable)",inline = False)
        embed31.set_thumbnail(url = "https://lh3.googleusercontent.com/proxy/zLxaJjWwQRHOJEK64oyyGNlYzJ4bDo5x_waU9i9l_Sw3vpVRvlPS-mMI0WkYa2BSZ2VUZYFkA7XcY-OZOT52PKyQeikhLveFe7LQqFz9T9HI")
        await ctx.send(embed = embed31)
    elif element == "Zinc" or element == "Zinc" or element == "30":
        embed32 = discord.Embed(title = "`ZINC`", color = discord.Colour.blue())
        embed32.add_field(name = "❯ **Name**", value = "Zinc")
        embed32.add_field(name = "❯ **Atomic Symbol**", value = "Zn",inline = True)
        embed32.add_field(name = "❯ **Atomic Number**", value = "30")
        embed32.add_field(name = "❯ **Atomic Mass**", value = "65.38u",inline = True)
        embed32.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed32.add_field(name = "❯ **Colour**", value = "Slate Gray",inline = True)
        embed32.add_field(name = "❯ **Valency**", value = "2")
        embed32.add_field(name = "❯ **First Ionization eZnrgy**", value = "906.4 KJ/mol",inline = True)
        embed32.add_field(name = "❯ **Atomic Radius**", value = "135 pm")
        embed32.add_field(name = "❯ **Isotopes**", value = "Zn (mass = 64, 48.63%), Zn (mass = 65, unstable)",inline = False)
        embed32.set_thumbnail(url = "https://finemetalrooftech.com/wp-content/uploads/2013/01/Zinc-element.jpg")
        await ctx.send(embed = embed32)
    elif element == "Germanium" or element == "Germanium" or element == "32":
        embed33 = discord.Embed(title = "`GERMANIUM`", color = discord.Colour.blue())
        embed33.add_field(name = "❯ **Name**", value = "Germanium")
        embed33.add_field(name = "❯ **Atomic Symbol**", value = "Ge",inline = True)
        embed33.add_field(name = "❯ **Atomic Number**", value = "32")
        embed33.add_field(name = "❯ **Atomic Mass**", value = "72.63u",inline = True)
        embed33.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed33.add_field(name = "❯ **Colour**", value = "Gray",inline = True)
        embed33.add_field(name = "❯ **Valency**", value = "4")
        embed33.add_field(name = "❯ **First Ionization energy**", value = "762 KJ/mol",inline = True)
        embed33.add_field(name = "❯ **Atomic Radius**", value = "125 pm")
        embed33.add_field(name = "❯ **Isotopes**", value = "Ge (mass = 74, 36.73%), Ge (mass = 68, unstable)",inline = False)
        embed33.set_thumbnail(url = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmg5IQ8PhBLQKfGZBqYeaNU4feQSheTK80ww&usqp=CAU")
        await ctx.send(embed = embed33)
    elif element == "Arsenic" or element == "arsenic" or element == "33":
        embed34 = discord.Embed(title = "`ARSENIC`", color = discord.Colour.blue())
        embed34.add_field(name = "❯ **Name**", value = "Arsenic")
        embed34.add_field(name = "❯ **Atomic Symbol**", value = "As",inline = True)
        embed34.add_field(name = "❯ **Atomic Number**", value = "33")
        embed34.add_field(name = "❯ **Atomic Mass**", value = "74.921595u",inline = True)
        embed34.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed34.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed34.add_field(name = "❯ **Valency**", value = "5")
        embed34.add_field(name = "❯ **First Ionization energy**", value = "947 KJ/mol",inline = True)
        embed34.add_field(name = "❯ **Atomic Radius**", value = "115 pm")
        embed34.add_field(name = "❯ **Isotopes**", value = "As (mass = 75, 100%), As (mass = 73, unstable)",inline = False)
        embed34.set_thumbnail(url = "https://media.istockphoto.com/photos/arsenic-chemical-element-periodic-table-symbol-3d-render-picture-id1097469544?k=6&m=1097469544&s=170667a&w=0&h=mAAmm96Ihn2C81f0M5ms35g3z2ra7895rrHtcoVLNEg=")
        await ctx.send(embed = embed34)
    elif element == "Selenium" or element == "selenium" or element == "34":
        embed35 = discord.Embed(title = "`SELENIUM`", color = discord.Colour.blue())
        embed35.add_field(name = "❯ **Name**", value = "Selenium")
        embed35.add_field(name = "❯ **Atomic Symbol**", value = "Se",inline = True)
        embed35.add_field(name = "❯ **Atomic Number**", value = "34")
        embed35.add_field(name = "❯ **Atomic Mass**", value = "78.971u",inline = True)
        embed35.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed35.add_field(name = "❯ **Colour**", value = "Gray",inline = True)
        embed35.add_field(name = "❯ **Valency**", value = "6")
        embed35.add_field(name = "❯ **First Ionization energy**", value = "941 KJ/mol",inline = True)
        embed35.add_field(name = "❯ **Atomic Radius**", value = "115 pm")
        embed35.add_field(name = "❯ **Isotopes**", value = "Se (mass = 80, 49.61%), Se (mass = 79, unstable)",inline = False)
        embed35.set_thumbnail(url = "https://pixfeeds.com/images/science/chemistry/1280-482518545-selenium-element-of-periodic-table.jpg")
        await ctx.send(embed = embed35)
    elif element == "Bromine" or element == "bromine" or element == "35":
        embed36 = discord.Embed(title = "`BROMINE`", color = discord.Colour.blue())
        embed36.add_field(name = "❯ **Name**", value = "Bromine")
        embed36.add_field(name = "❯ **Atomic Symbol**", value = "Br",inline = True)
        embed36.add_field(name = "❯ **Atomic Number**", value = "35")
        embed36.add_field(name = "❯ **Atomic Mass**", value = "79.904u",inline = True)
        embed36.add_field(name = "❯ **Phase at STP**", value = "Liquid")
        embed36.add_field(name = "❯ **Colour**", value = "Red",inline = True)
        embed36.add_field(name = "❯ **Valency**", value = "5")
        embed36.add_field(name = "❯ **First Ionization energy**", value = "1139.9 KJ/mol",inline = True)
        embed36.add_field(name = "❯ **Atomic Radius**", value = "115 pm")
        embed36.add_field(name = "❯ **Isotopes**", value = "Br (mass = 79, 50.69%), Br (mass = 81, 49.31%), Br (mass = 77, unstable)",inline = False)
        embed36.set_thumbnail(url = "https://media.visualstories.com/images/science/chemistry/640-482518761-bromine-element.jpg")
        await ctx.send(embed = embed36)
    elif element == "Krypton" or element == "krypton" or element == "36":
        embed37 = discord.Embed(title = "`KRYPTON`", color = discord.Colour.blue())
        embed37.add_field(name = "❯ **Name**", value = "Krypton")
        embed37.add_field(name = "❯ **Atomic Symbol**", value = "Kr",inline = True)
        embed37.add_field(name = "❯ **Atomic Number**", value = "36")
        embed37.add_field(name = "❯ **Atomic Mass**", value = "83.789u",inline = True)
        embed37.add_field(name = "❯ **Phase at STP**", value = "Gas")
        embed37.add_field(name = "❯ **Colour**", value = "Colorless",inline = True)
        embed37.add_field(name = "❯ **Valency**", value = "2")
        embed37.add_field(name = "❯ **First Ionization energy**", value = "1350.8 KJ/mol",inline = True)
        embed37.add_field(name = "❯ **Atomic Radius**", value = "88 pm")
        embed37.add_field(name = "❯ **Isotopes**", value = "Kr (mass = 84, 57%), Kr (mass = 81, unstable)",inline = False)
        embed37.set_thumbnail(url = "https://d2cbg94ubxgsnp.cloudfront.net/Pictures/480x270//2/3/4/135234_pt_element36.jpg")
        await ctx.send(embed = embed37)
    elif element == "Rubidium" or element == "rubidium" or element == "37":
        embed38 = discord.Embed(title = "`RUBIDIUM`", color = discord.Colour.blue())
        embed38.add_field(name = "❯ **Name**", value = "Rubidium")
        embed38.add_field(name = "❯ **Atomic Symbol**", value = "Rb",inline = True)
        embed38.add_field(name = "❯ **Atomic Number**", value = "37")
        embed38.add_field(name = "❯ **Atomic Mass**", value = "85.4768u",inline = True)
        embed38.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed38.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed38.add_field(name = "❯ **Valency**", value = "1")
        embed38.add_field(name = "❯ **First Ionization energy**", value = "403 KJ/mol",inline = True)
        embed38.add_field(name = "❯ **Atomic Radius**", value = "235 pm")
        embed38.add_field(name = "❯ **Isotopes**", value = "Rb (mass = 85, 72.17%), Rb (mass = 87, unstable)",inline = False)
        embed38.set_thumbnail(url = "https://lh3.googleusercontent.com/proxy/Yyd72RuwAnHHPoP5CpZB--rVnroUL1KFQdpmzfcstaZbwNnWAmKs8xZXs93qmhUbYv75cKcFMq2uDKoliPpAHeGRJF1WXDDREij3QeLvLNZKZA")
        await ctx.send(embed = embed38)
    elif element == "Strontium" or element == "strontium" or element == "38":
        embed39 = discord.Embed(title = "`STRONTIUM`", color = discord.Colour.blue())
        embed39.add_field(name = "❯ **Name**", value = "Strontium")
        embed39.add_field(name = "❯ **Atomic Symbol**", value = "Sr",inline = True)
        embed39.add_field(name = "❯ **Atomic Number**", value = "38")
        embed39.add_field(name = "❯ **Atomic Mass**", value = "87.62u",inline = True)
        embed39.add_field(name = "❯ **Phase at STP**", value = "Solid")
        embed39.add_field(name = "❯ **Colour**", value = "Silver",inline = True)
        embed39.add_field(name = "❯ **Valency**", value = "2")
        embed39.add_field(name = "❯ **First Ionization energy**", value = "549.5 KJ/mol",inline = True)
        embed39.add_field(name = "❯ **Atomic Radius**", value = "200 pm")
        embed39.add_field(name = "❯ **Isotopes**", value = "Sr (mass = 88, 82.58%), Sr (mass = 90, unstable)",inline = False)
        embed39.set_thumbnail(url = "https://img.myloview.pl/tapety/stront-pierwiastek-chemiczny-symbol-z-okresowym-wyswietlane-na-czarnym-szescianu-160-79174876.jpg")
        await ctx.send(embed = embed39)	
    else:
        await ctx.send("Invalid Input! Try something else!")

client.run("<bot token>")
